# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: ilrs-service
spec:
  selector:
    app: ilrs-deployment
  type: ClusterIP
  ports:
  - name: ilrs-service
    protocol: TCP
    port: 80
    targetPort: ilrs-http-port
---

